import{i as s,S as m}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();function d(i){const o=document.querySelector(".gallery-list");if(!o){console.error("Gallery element not found in the DOM.");return}o.innerHTML="";const n=i.map(({webformatURL:t,largeImageURL:e,tags:r,likes:a,views:u,comments:f,downloads:p})=>`<li class="gallery-item">
        <a href="${e}" class="gallery-link">
          <img src="${t}" alt="${r}" loading="lazy" />
        </a>
        <div class="info">
            <p><b>Likes:</b> ${a}</p>
            <p><b>Views:</b> ${u}</p>
            <p><b>Comments:</b> ${f}</p>
            <p><b>Downloads:</b> ${p}</p>
          </div>
      </li>`).join("");o.innerHTML=n}function g(i){const o="47381737-77b313e1304caa98d6d0e16f2";if(!i.trim()){s.warning({title:"Caution",position:"bottomRight",backgroundColor:"#FF0000",message:"Please enter a search word!"});return}const n=new URLSearchParams({key:o,q:i,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`https://pixabay.com/api/?${n}`).then(t=>{if(!t.ok)throw new Error(t.statusText);return t.json()}).then(t=>{if(console.log("data.hits",t.hits),d(t.hits),y(),t.hits.length===0){s.show({title:"No results",position:"topRight",backgroundColor:"#cd0d0d",message:"Sorry, there are no images matching your search query. Please, try again!"});return}}).catch(t=>{console.log(t.message)})}function y(){new m(".gallery-list a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8})}const c=document.querySelector("form"),h=c.querySelector("input");c.addEventListener("submit",b);const l=document.querySelector(".gallery-list");function b(i){i.preventDefault();const o=h.value.trim();L(),w(),g(o)}function L(){const i=document.querySelector(".gallery-list");i&&(i.innerHTML="")}function w(){l&&(l.innerHTML='<p class="loading">Loading images, please wait...</p>')}
//# sourceMappingURL=index.js.map
